//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paquete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paquete()
        {
            this.Factura = new HashSet<Factura>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public double Precio { get; set; }
        public int CantDias { get; set; }
        public System.DateTime FechaViaje { get; set; }
        public bool Estado { get; set; }
        public int Lugares { get; set; }
        public bool Activo { get; set; }
        public int PaisId { get; set; }
        public int ProvinciaId { get; set; }
        public bool Nacional { get; set; }
        public double Cotizacion { get; set; }
        public bool Visa { get; set; }
        public double Impuesto { get; set; }
        public int Cuotas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Provincia Provincia { get; set; }
    }
}
